### ISSUE TITLE
qualisys_python_sdk  on Ubuntu

### ISSUE THREAD

**Issue by lalal321** [qualisys/qualisys_python_sdk#2]
Hello, sorry to bother you. I am a student using the Qualisys Motion capture for the qualisys_python_sdk on  ubuntu system, and I execute the command as you :

python -m pip install pip --upgrade # Upgrade to latest pip
python -m pip install qtm

but there're problems to warning me, as following:

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/twisted/test/raiser.c -o build/temp.linux-x86_64-2.7/src/twisted/test/raiser.o

src/twisted/test/raiser.c:4:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Can you help me ? thank you ！！！

**Comment by lalal321** [comment]
Oh, sorry, I have jumped the above problem, and now it tips me that : 

Successfully built twisted
Installing collected packages: constantly, incremental, attrs, Automat, twisted
Exception:
Traceback (most recent call last):

Is it all right ?
thank you !

**Comment by mgejke** [comment]
Hi, 

Sorry for the late answer, didn't get any notifications. 

The qtm package uses another package called twisted, to install this you have to compile some stuff(which is done automatically for you) but it requires some dependencies. 

To fix the "src/twisted/test/raiser.c:4:20: fatal error: Python.h: No such file or directory" error you should do:
"sudo apt-get install python-dev" and try again.
