### ISSUE TITLE
basic_example.py not working with version 2.1.0

### ISSUE THREAD

**Issue by Yunusbcr** [qualisys/qualisys_python_sdk#20]
I have updated qtm python sdk to version 2.1.0 and I have connection problem now. Version 2.0.6 was working fine. But with 2.1.0 when I run basic_example it gives me error.

python3 basic_example.py 

2021-04-15 09:58:00,434 - qtm - INFO - Connected
2021-04-15 09:58:00,498 - qtm - ERROR - <class 'Exception'>

**Comment by EmilRosenquist** [comment]
Hello @Yunusbcr, The error message was a bug in the sdk not logging the actual exception. (fixed #21).
 
My guess is that your QTM does not support protocol version 1.22 (You need QTM 2021.1 for this).
As you can see the default in connect is 1.22 https://github.com/qualisys/qualisys_python_sdk/blob/99818140f6fb3e70bd321364d0b09582c3dee9fe/qtm/qrt.py#L330

To run v2.1.0 either specify a lower protocol version in the connect call or upgrade to QTM 2021.1.
