### ISSUE TITLE
basic_example wrong on ubuntu

### ISSUE THREAD

**Issue by lalal321** [qualisys/qualisys_python_sdk#3]
Hello, I executed the example : basic_example, but it tips me that following message:

Connected to QTM with Version set to 1.13
'You must be master to issue this command'
Connection was closed cleanly.

What should I do ? Thank you !

**Comment by mgejke** [comment]
That sounds odd. What version of QTM are you running?

Nothing in that script should require that you are master, but you could try to become master by sending the command:
`self.connection.take_control('password')`  before `self.connection.start(...` where password is the password you have setup in qtm, Project Options -> Real-Time Output -> Client Control -> Password.
