### ISSUE TITLE
Streaming examples broken in latest release

### ISSUE THREAD

**Issue by jrieffel** [qualisys/qualisys_python_sdk#5]
The new release of the python SDK seems to use protocol 1.19, and therefore does not appear to work with QTM 2018.1 (4300), which only supports up to 1.18, and which as far as I can tell is the latest release of QTM.

**Comment by bavovk** [comment]
Has this been solved in the new version of QTM 2019.1 (4400)?

I am trying to run the stream_6dof_example.py but get a 'Failed to load measurement'  raised. Starting a new realtime works fine though...

**Comment by nilzilch** [comment]
The examples are tested and works in the latest version (v 2.0.5).
