### ISSUE TITLE
Start capture 

### ISSUE THREAD

**Issue by Simon-Bastide** [qualisys/qualisys_python_sdk#6]
Hi,

I'm actually able to stream frames in real time but i would like to start a new capture in QTM using the python sdk. 
I setup the connection as you did in your advanced_exemple file. It works fine until i'm trying to use `connection.set_qtm_event`

I guess this is not the way to use it. Do you have any recommandation to take control of qtm and manage capture (start, stop, set filename) ?

Here the code i'm using :
```
connection = await qtm.connect(127.0.0.1, version="1.16")

async with qtm.TakeControl(connection, "password"):
    #logger.info('Password OK')
    state = await connection.get_state()
    if state != qtm.QRTEvent.EventConnected:
        await connection.new()
        try:
            await connection.await_event(qtm.QRTEvent.EventConnected, timeout=10)
        except asyncio.TimeoutError:
            #logger.warning("Failed to start new measurement | asyncio.TimeoutError")
            return -1

    await connection.set_qtm_event(qtm.QRTEvent.EventCaptureStarted)
```

Thank you !

**Comment by mlveggo** [comment]
Hi,

Sorry for the response delay.

You should use that start, stop and save commands to be able to do what you want.
The set_qtm_event is for creating events in the qtm timeline.

Morgan
